# Databricks App Configuration for TCA Schedule Optimizer
name: tca-schedule-optimizer
display_name: "TCA Schedule Optimizer"

# Runtime configuration
env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"

# Startup command
command: ["npm", "start"]

# Resource requirements
resources:
  - name: default-warehouse
    type: sql-warehouse
    permission: CAN_USE
    
# App metadata
description: "Comprehensive schedule optimization dashboard for franchise operations with geospatial route management and statistical analysis"
version: "1.0.0"