[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { NODE_ENV = "production", PORT = "5000" }